import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/global/Navbar'

export const metadata: Metadata = {
  title: 'Shilatjit — Energy Drink Can',
  description: 'Generated by create next app',
  icons: '/images/icon.jpeg'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='font-primary'>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
